### ISSUE TITLE
Add multiprocess CPU support

### ISSUE THREAD

**Issue by 1cosmologist** [marcelo-alvarez/lpt4py#3]
Current `lpt4py` code heavily leverages JAX `distributed` and `sharding` for multiprocess backend required for native JAX FFTs on GPUs. JAX `distributed` only works for GPU and TPU backend devices (see here: https://github.com/google/jax/issues/11182 ). So, at the moment `lpt4py` cannot run multiprocess (multi-node) tasks on CPU-only systems (like Perlmutter CPU nodes). 

Down the road we would want to add `mpi4py-fft` based distributed, multiprocess FFT support on CPUs.

**Comment by marcelo-alvarez** [comment]
@1cosmologist transferred to https://github.com/exgalsky/lpt/issues/2, closing.
